#include "menu.h"
#include <stdio.h>
#include <stdlib.h>
#include "windows.h"
///MENUES
int menuMain () ///MENU PRINCIPAL PARA EL MAIN
{
    system("color 1F");
    int input;
    printf("\n");
    system("PAUSE");
    system("cls");
    gotoXY(20, 7);
    printf("       ___\n");
    gotoXY(20, 8);
    printf("     o|* *|o\n");
    gotoXY(20, 9);
    printf("     o|* *|o\n");
    gotoXY(20, 10);
    printf("     o|* *|o\n");
    gotoXY(20, 11);
    printf("      \\===/\n");
    gotoXY(20, 12);
    printf("       |||\n");
    gotoXY(20, 13);
    printf("       |||\n");
    gotoXY(20, 14);
    printf("       |||\n");
    gotoXY(20, 15);
    printf("       |||\n");
    gotoXY(20, 16);
    printf("      _|||_\n");
    gotoXY(20, 17);
    printf("   /   |||   \\\n");
    gotoXY(20, 18);
    printf("  /    |||    \\\n");
    gotoXY(20, 19);
    printf(" |     |||     |\n");
    gotoXY(20, 20);
    printf("  \\   (|||)   /\n");
    gotoXY(20, 21);
    printf("   |   |||   |\n");
    gotoXY(20, 22);
    printf("  /    |||    \\\n");
    gotoXY(20, 23);
    printf(" /     |||     \\\n");
    gotoXY(20, 24);
    printf("/      |||      \\\n");
    gotoXY(20, 25);
    printf("|     [===]     |\n");
    gotoXY(20, 26);
    printf(" \\             /\n");
    gotoXY(20, 27);
    printf("  '.         .'\n");
    gotoXY(20, 28);
    printf("    '-------'\n");
		gotoXY(85, 7);
    printf("       ___\n");
    gotoXY(85, 8);
    printf("     o|* *|o\n");
    gotoXY(85, 9);
    printf("     o|* *|o\n");
    gotoXY(85, 10);
    printf("     o|* *|o\n");
    gotoXY(85, 11);
    printf("      \\===/\n");
    gotoXY(85, 12);
    printf("       |||\n");
    gotoXY(85, 13);
    printf("       |||\n");
    gotoXY(85, 14);
    printf("       |||\n");
    gotoXY(85, 15);
    printf("       |||\n");
    gotoXY(85, 16);
    printf("      _|||_\n");
    gotoXY(85, 17);
    printf("   /   |||   \\\n");
    gotoXY(85, 18);
    printf("  /    |||    \\\n");
    gotoXY(85, 19);
    printf(" |     |||     |\n");
    gotoXY(85, 20);
    printf("  \\   (|||)   /\n");
    gotoXY(85, 21);
    printf("   |   |||   |\n");
    gotoXY(85, 22);
    printf("  /    |||    \\\n");
    gotoXY(85, 23);
    printf(" /     |||     \\\n");
    gotoXY(85, 24);
    printf("/      |||      \\\n");
    gotoXY(85, 25);
    printf("|     [===]     |\n");
    gotoXY(85, 26);
    printf(" \\             /\n");
    gotoXY(85, 27);
    printf("  '.         .'\n");
    gotoXY(85, 28);
    printf("    '-------'\n");

    gotoXY(49, 7);
    printf("LA DISQUERA DEL CHABON");
    gotoXY(45, 10);
    printf("=============================");
    gotoXY(45, 11);
    printf("         Bienvenido");
    gotoXY(45, 12);
    printf("=============================");
    gotoXY(45, 13);
    printf("1-CARGAR UN ARTISTA CON SU ALBUM");
    gotoXY(45, 14);
    printf("2-AGREGAR ALBUM A ARTISTA");
    gotoXY(45, 15);
    printf("3-CONSULTAR DATOS DEL SISTEMA");
    gotoXY(45, 16);
    printf("4-AGREGAR Y DEVENGAR VENTAS");
    gotoXY(45, 17);
    printf("5-DAR DE BAJA O ALTA UN ALBUM");
    gotoXY(45, 18);
    printf("6-DAR DE BAJA O ALTA UN ARTISTA");
    gotoXY(45, 19);
    printf("7-BUSCAR ARTISTA POR NOMBRE");
    gotoXY(45, 20);
    printf("8-ELEJIR ORDENAMIENTO");
    gotoXY(45, 21);
    printf("9-MODIFICAR UN ARTISTA O UN ALBUM");
    gotoXY(45, 22);
    printf("10-REPRODUCIR UNA CANCION");
    gotoXY(45, 23);
    printf("ELIJE UNA OPCION:   ");
    gotoXY(45, 24);
    scanf("%d", &input);
    system("cls");
    return input;
}

int menuOrdenamientos ()   ///MENU PARA LOS ORDENAMIENTOS
{
    system("cls");
    int input;

    gotoXY(20, 11);
    printf("                              #   @@=                                        \n");
    gotoXY(20, 12);
    printf("                             =      @@+                                      \n");
    gotoXY(20, 13);
    printf("             @@@@%#@+      :         =@@*                                    \n");
    gotoXY(20, 14);
    printf("           @@@@@@@@@@@  :@=            @@@@-      @@@@@=                     \n");
    gotoXY(20, 15);
    printf("           @@@@@@@@@@@@@                @@@@@.     @@@@                      \n");
    gotoXY(20, 16);
    printf("          @@@@@@@@@@@@@@@              @@@@@@@@.   @@@@=                     \n");
    gotoXY(20, 17);
    printf("            @@@@@@@@@@@@               @@@@  %@@@   @@@@*                    \n");
    gotoXY(20, 18);
    printf("            @@@@@@@@@@@@@@            @@@:     @@@%-  @@@@                   \n");
    gotoXY(20, 19);
    printf("                 @@@@@@@@@@          @@@@@@      @@@#% *@@@@                 \n");
    gotoXY(20, 20);
    printf("                 @@@@@@@@@@@@@@*   @@@@@@@@       =@@@@. @@@@@               \n");
    gotoXY(20, 21);
    printf("                 @@@@@@@@@@@@@@@@@@@@@@@@           @@@@# :@@@@@             \n");
    gotoXY(20, 22);
    printf("                 @@@@@@@@@@@@@@@@@@@@@@@          %@@@@@@@@  @@@@            \n");
    gotoXY(20, 23);
    printf("                  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@: #@@@@@@@=            \n");
    gotoXY(20, 24);
    printf("                  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@        -@@@@@              \n");
    gotoXY(20, 25);
    printf("                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                            \n");
    gotoXY(20, 26);
    printf("                    @@@@@@@@@@@@@@@@@*        \n");
    gotoXY(20, 27);
    printf("                    @@@@@@@@@@@@@@@@@:     \n");
    gotoXY(20, 28);
    printf("                    @@@@@@@@@@@@@@@@@%..      \n");


    gotoXY(45, 2);
    printf("LISTAS:");
    gotoXY(45, 3);
    printf("1-ALBUMES MAS VENDIDOS");
    gotoXY(45, 4);
    printf("2-ALBUMES MAS NUEVOS");
    gotoXY(45, 5);
    printf("3-ARTISTAS CON MAYOR CANTIDAD DE ALBUMES");
    gotoXY(45, 6);
    printf("4-ARTISTAS ALFABETICO");
    gotoXY(45, 7);
    printf("5-ALBUMES ALFABETICO");
    gotoXY(45, 8);
    printf("0-SALIR DEL MENU");
    gotoXY(45, 9);
    printf("ELIJE UNA OPCION: ");
    gotoXY(45, 10);
    scanf("%d", &input);
    system("cls");
    return input;
}

int menuConsultas ()
{
    system("cls");
    int input = 0;

    gotoXY(15, 0);
    printf("         .---   ");
    gotoXY(15, 1);
    printf("        :-=--       ");
    gotoXY(15, 2);
    printf("       .-==-:       ");
    gotoXY(15, 3);
    printf("       ::=+--       ");
    gotoXY(15, 4);
    printf("      ..-++--       ");
    gotoXY(15, 5);
    printf("      .:=++=-.      ");
    gotoXY(15, 6);
    printf("       .-++:       ");
    gotoXY(15, 7);
    printf("        .%%-        ");
    gotoXY(15, 8);
    printf("        :%%-        ");
    gotoXY(15, 9);
    printf("        :##-        ");
    gotoXY(15, 10);
    printf("        -%%-        ");
    gotoXY(15, 11);
    printf("        -%%=        ");
    gotoXY(15, 12);
    printf("        =%%=        ");
    gotoXY(15, 13);
    printf("        =%#=        ");
    gotoXY(15, 14);
    printf("        =##=        ");
    gotoXY(15, 15);
    printf("        +##+        ");
    gotoXY(15, 16);
    printf(" :@@    +%%+        ");
    gotoXY(15, 17);
    printf(" =@@:   +%%+    =:  ");
    gotoXY(15, 18);
    printf(" .@@@@=-%%%+    . : ");
    gotoXY(15, 19);
    printf("  =@@@* +##*:--:  : ");
    gotoXY(15, 20);
    printf("   %@@@.-##-     =  ");
    gotoXY(15, 21);
    printf("   *@@@. -:.    :. ");
    gotoXY(15, 22);
    printf("   #@@#  -:.    :.  ");
    gotoXY(15, 23);
    printf("  =@@%   -:.     :  ");
    gotoXY(15, 24);
    printf(" +@@@+   -:.      - ");
    gotoXY(15, 25);
    printf("=@@@@%.  -:.      .:");
    gotoXY(15, 26);
    printf("@@@@@@@#+*++-    -");
    gotoXY(15, 27);
    printf("%@@@@@@@@@@@@#=+*: -");
    gotoXY(15, 28);
    printf(".#@@@@@@@@@@@@@@%@+.");
    gotoXY(15, 29);
    printf("   -%@@@@@@@@@%*.   ");


    gotoXY(45, 11);
    printf("CONSULTAS: ");
    gotoXY(45, 12);
    printf("1-VER TODOS LOS ARTISTAS");
    gotoXY(45, 13);
    printf("2-VER TODOS LOS ALBUMES");
    gotoXY(45, 14);
    printf("3-VER LA CAJA");
    gotoXY(45, 15);
    printf("4-VER SOLO ARTISTAS ACTIVOS");
    gotoXY(45, 16);
    printf("5-VER SOLO ALBUMES DISPONIBLES");
    gotoXY(45, 17);
    printf("6-VER ARTISTAS INACTIVOS");
    gotoXY(45, 18);
    printf("7-VER ALBUMES AGOTADOS");
    gotoXY(45, 19);
    printf("8-VER LOS DISCO DE UN ARTISTA");
    gotoXY(45, 20);
    printf("9-VER LOS ARTISTAS DE UN GENERO");
    gotoXY(45, 21);
    printf("0-SALIR DEL MENU");
    gotoXY(45, 22);
    printf("ELIJE UNA OPCION: ");


    gotoXY(85, 0);
    printf("         .---   ");
    gotoXY(85, 1);
    printf("        :-=--       ");
    gotoXY(85, 2);
    printf("       .-==-:       ");
    gotoXY(85, 3);
    printf("       ::=+--       ");
    gotoXY(85, 4);
    printf("      ..-++--       ");
    gotoXY(85, 5);
    printf("      .:=++=-.      ");
    gotoXY(85, 6);
    printf("       .-++:        ");
    gotoXY(85, 7);
    printf("        .%%-        ");
    gotoXY(85, 8);
    printf("        :%%-        ");
    gotoXY(85, 9);
    printf("        :##-        ");
    gotoXY(85, 10);
    printf("        -%%-        ");
    gotoXY(85, 11);
    printf("        -%%=        ");
    gotoXY(85, 12);
    printf("        =%%=        ");
    gotoXY(85, 13);
    printf("        =%#=        ");
    gotoXY(85, 14);
    printf("        =##=        ");
    gotoXY(85, 15);
    printf("        +##+        ");
    gotoXY(85, 16);
    printf(" :@@    +%%+        ");
    gotoXY(85, 17);
    printf(" =@@:   +%%+    =:  ");
    gotoXY(85, 18);
    printf(" .@@@@=-%%%+    . : ");
    gotoXY(85, 19);
    printf("  =@@@* +##*:--:  : ");
    gotoXY(85, 20);
    printf("   %@@@.-##-     =  ");
    gotoXY(85, 21);
    printf("   *@@@. -:.    :.  ");
    gotoXY(85, 22);
    printf("   #@@#  -:.    :.  ");
    gotoXY(85, 23);
    printf("  =@@%   -:.     :  ");
    gotoXY(85, 24);
    printf(" +@@@+   -:.      - ");
    gotoXY(85, 25);
    printf("=@@@@%.  -:.      .:");
    gotoXY(85, 26);
    printf("@@@@@@@#+*++-    -");
    gotoXY(85, 27);
    printf("%@@@@@@@@@@@@#=+*: -");
    gotoXY(85, 28);
    printf(".#@@@@@@@@@@@@@@%@+.");
    gotoXY(85, 29);
    printf("   -%@@@@@@@@@%*.   ");


    gotoXY(45, 23);

    scanf("%d", &input);
    system("cls");
    return input;
}

int menuCanciones() {
    int input = 0;
    printf("\nLISTA DE CANCIONES:");
    printf("\n1-Don't Look Back In Anger(Oasis)");
    printf("\n2-Scar Tissue (RHCP)");
    printf("\n3-She Said(The Beatles)");
    printf("\n4-Ya nadie va escuchar tu remera (Patricio Rey)");
    printf("\n5-Come As You Are(Nirvana)");
    printf("\n6-Dancing Days(Led Zeppelin)");
    printf("\n7-Wish You Were Here (Pink Floyd)");
    printf("\n8-Gustavo Cerati (Adios)");
    printf("\n9-Bajan (Spinetta)");
    printf("\n\nELIGE UNA OPCION: ");
    scanf("%d", &input);
    return input;
}

/// Función para mover el cursor a una posición específica en la consola
void gotoXY(int x, int y)
{
    COORD coord;
    coord.X = x;
    coord.Y = y;
    SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE), coord);
}
